### ISSUE TITLE
Update fio-api

### ISSUE THREAD

**Issue by heximcz** [mhujer/fio-api-bundle#1]
Hello,

is possible update fio api to v4+ ?
Working this bundle with Symfony v3+ ?

Thank you.

**Comment by mhujer** [comment]
I forgot about this, thanks for letting me know!

**Comment by mhujer** [comment]
@heximcz  I've prepared a branch, can you please try if it works for you? (I'm no longer personally using the bundle)

Use `"dev-mh-sf3"` as a version constraint in `composer.json`.

**Comment by heximcz** [comment]
Tested, yes this branch working fine.

**Comment by mhujer** [comment]
@heximcz Perfect. I've merged it and released it as 2.0.0
